### ISSUE TITLE
Describe what a "appropriate" setting for HORIZON_POOL is 

### ISSUE THREAD

**Issue by rnestler** [carrotIndustries/horizon#1]
The README states:
> HORIZON_POOL needs to be set appropriately for all commands below

I didn't really get what the horizon pool should be. I guess the path to a clone of https://github.com/carrotIndustries/horizon-pool?

Maybe describe the concept of the pool.

**Comment by rnestler** [comment]
I just noticed the https://github.com/carrotIndustries/horizon#get-started section which explains most  of it. Maybe just restructure the README.

**Comment by carrotIndustries** [comment]
Not necessary for normal use anymore, use project manager.
