### ISSUE TITLE
Precompiled headers

### ISSUE THREAD

**Issue by jeanthom** [carrotIndustries/horizon#100]
Build time is currently huge. On a dual-core multi-threaded CPU, it is around 11 minutes. We may be able to cut that time using precompiled headers :
 * https://gcc.gnu.org/onlinedocs/gcc/Precompiled-Headers.html
 * http://itscompiling.eu/2017/01/12/precompiled-headers-cpp-compilation/

**Comment by jeanthom** [comment]
https://github.com/jeanthom/horizon/tree/precompiled-headers

I got compile time to around 8-9 minutes. However I don't like the principle of precompiled headers for a whole project.

**Comment by carrotIndustries** [comment]
>  However I don't like the principle of precompiled headers for a whole project.

Me neither. Closing since probably not worth the effort.
