### ISSUE TITLE
Schematic editor : net name field has weird glitches

### ISSUE THREAD

**Issue by jeanthom** [carrotIndustries/horizon#108]
![capture d ecran_2018-02-08_23-58-15](https://user-images.githubusercontent.com/25333063/36002941-48959d98-0d2c-11e8-8402-0ab3717c2fdc.png)

Text orientation is right-to-left, and sometime becomes a password field.

**Comment by carrotIndustries** [comment]
The entries as well as most of the other editors are right-aligned to separate their content from the header above.

The dots went there to provide some sort of "editing in progress" feedback. No idea if that's still required.

**Comment by jeanthom** [comment]
I think the dots are confusing as a progress indicator, a [Gtk::Spinner](https://developer.gnome.org/gtkmm/stable/classGtk_1_1Spinner.html) seems more appropriate
