### ISSUE TITLE
[UI] Floating point convention

### ISSUE THREAD

**Issue by atoav** [carrotIndustries/horizon#115]
Right now different standards exist within the program. Some parts of the software want to have a comma based float like `3,14159265359` and some (e.g. the courtyard parameter) want to have a dot delimiter like`3.14159265359`.  

There are three ways of dealing with this:  
1. Ignore it and let the users sort it out
2. Unify it and settle for either `.` or `,`
3. Allow both

Wether a dot or a comma is used typically depends on the users locale, what they are used to and in some cases (like mine) what kind of software they used before and what the conventions where there. Keeping that in mind it makes sense to allow _both_ as a delimiter, always ignoring everything but the rightmost delimiter (if you have `9.000,99` it is over 9000 and not `9.00099`). This makes copy and pasting easier and faster and users don't have to remember which format horizon used again. This is one of the things I always forget about each software package I use, because everybody treats it differently.  

If this is something that has to be done to all numeric input fields, I would also suggest adding rudimentary math functionality to these fields:
- If you enter `3.5*2` it will evaluate to `7`
- If you enter `5/2` it will evaluate to `2.5`
- If you enter `10.1324623+0.1` it will evaluate to `10.2324623`

**Edit:** Blender Text field for inspiration (Dragging changes values like a slider – also neat, but probably not needed here)
![blender_text_field](https://user-images.githubusercontent.com/6620266/36399757-ab17cf32-15cd-11e8-92cb-76fafd358639.gif)

**Comment by greenscreenflicker** [comment]
I love the idea of rudementary math, as it opens the possibility of not having a calculator next to the desk. Would really save some time.
