### ISSUE TITLE
Feature Request: Rename/Naming Action

### ISSUE THREAD

**Issue by atoav** [carrotIndustries/horizon#123]
When editing a lot of packages I found the (pad) naming field to come in my way more often than not. This has also the reason that the field looses focus when the mouse moves away from it, which is sort of unexpected behaviour.  

I would suggest a broader solution however: a Action that allows for quick editing of a certain default field that is related to Name or Reference Designator. This would of course be something different in every different context (Change Text of a Text Field etc).

**Comment by carrotIndustries** [comment]
We already have a tool that does something similar: Enter datum (press enter to start this tool) cbd889bcefebaa3087f381723e42012b3fe67a14 adds editing text and now edits pad names instead of pad position

**Comment by atoav** [comment]
Ah very cool, I didn't know that it would change it's functionality with context
