### ISSUE TITLE
Pool-mgr: Git error 12

### ISSUE THREAD

**Issue by greenscreenflicker** [carrotIndustries/horizon#125]
![screenshot from 2018-03-12 20-59-33](https://user-images.githubusercontent.com/17407241/37306570-674471e0-2638-11e8-98b3-1e12282fca70.png)

**Comment by carrotIndustries** [comment]
That's odd, try adding 
```std::cout << "clone url " << clone_url << std::endl;```
at https://github.com/carrotIndustries/horizon/blob/master/src/pool-mgr/pool-mgr-app_win.cpp#L243 and see what it prints.

**Comment by greenscreenflicker** [comment]
@carrotIndustries 
Promts std::cout << "clone url " << clone_url << std::endl;

However, using ubuntu 17.10 now.

**Comment by carrotIndustries** [comment]
This is related to debian shipping libgit2 without TLS support: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=832798
