### ISSUE TITLE
Logo not displayed in ubuntu taskbar

### ISSUE THREAD

**Issue by greenscreenflicker** [carrotIndustries/horizon#126]
![image](https://user-images.githubusercontent.com/17407241/37306661-a89908a4-2638-11e8-868a-3a97eb34a556.png)
We have such a nice logo now. However in ubuntu it is not displayed.

**Comment by carrotIndustries** [comment]
That may be due to toe ubuntu panel trying to load the icon from the desktop file which isn't existing right now. As soon has we have properly packaged releases, this should go away.

**Comment by atoav** [comment]
![hor_icon](https://user-images.githubusercontent.com/6620266/37722044-67e277a6-2d2b-11e8-94a5-fa503d720bfd.png)  

I have a similar problem in Windows 10 (Started `horizon-pool-mgr.exe` and pinned it to the Task Bar). As you can see the Windows AeroPeek thingie displays the icon while the taskbar forgets about it as soon as you pin it).

**Comment by atoav** [comment]
For Windows 10 this issue has been fixed with d51f34a6b6ded83427ff2bbeef7a92c3b799b11c
Cannot tell wether this is true for Ubuntu

**Comment by greenscreenflicker** [comment]
@carrotIndustries @atoav Confirm fixed in ubuntu.
