### ISSUE TITLE
Icons not exactly square

### ISSUE THREAD

**Issue by carrotIndustries** [carrotIndustries/horizon#129]
@atoav While creating the ICO file with multiple sizes for windows I noticed that the sizes of some of the PNGs are off-by-one. For the small ones, it's just a matter of autocropping to fix this since the extra pixels are transparent, but with the 256x256 icon, that's not the case.

**Comment by atoav** [comment]
I think you found a rounding-error in adobe illustrator, my artboards are perfectly square...

I pushed a fixed PNG to [63264de](https://github.com/atoav/horizon-logo/commit/63264de4424863fa180d31c1b2f298a8821bef9c) in my [horizon-logo repository](https://github.com/atoav/horizon-logo)
