### ISSUE TITLE
Clickable icon does not appear

### ISSUE THREAD

**Issue by NotAFile** [carrotIndustries/horizon#130]
I think this is due to my window manager (i3), but horizon-prj-mgr does not show an icon in the top left like on the pictures.

Display Server: Xorg
Distribution: Fedora
Window Manager: i3

**Comment by carrotIndustries** [comment]
I'm using i3 as well and the application icon is there. Is the icon absent in other Gtk3 applications such as gnome-calculator?

**Comment by NotAFile** [comment]
yes, gnome-calculator does not show it either

**Comment by carrotIndustries** [comment]
Ok, so you may want to check `gtk-shell-shows-app-menu` and `gtk-decoration-layout` in your gtk `settings.ini`

**Comment by NotAFile** [comment]
I don't have a settings.ini file

**Comment by carrotIndustries** [comment]
Run `gtk-query-settings` and see for the aforementioned variables.
If `gtk-shell-shows-app-menu` is TRUE, add `gtk-shell-shows-app-menu=0` to the settings ini
If `gtk-decoration-layout` is doesn't contain menu, add `gtk-decoration-layout="menu:minimize,maximize,close"` to the settings ini

Then settings.ini goe in `~/.config/gtk-3.0/settings.ini`:

**Comment by carrotIndustries** [comment]
closing due to inacticity
