### ISSUE TITLE
[UI] Minor clarity issue with Powernet display styles

### ISSUE THREAD

**Issue by atoav** [carrotIndustries/horizon#134]
When dealing with powernets I cought myself twice (it has been some time inbetween) thinking: "I know what Ground is, I have a suspicion what a Antenna is, I have no idea what a Dot is and where the hell is Vcc and Vee?"  
![horizon_power_nets](https://user-images.githubusercontent.com/6620266/38466865-c6699bf8-3b2f-11e8-8ceb-8d418232a352.png)  
My problem solved itself once I realized that Dot, Antenna and Ground just refer to the _style_ of the symbol used. I think this can be a minor issue for other users as well. A quick fix would be adding some kind of header column like: 
```
Name                            Style
-----------------------------------------------
FOO                             Antenna
BAR                             Dot
GND                             Ground
```  

Downside is obviously screen space, but it adds conceptual clarity.

**Comment by carrotIndustries** [comment]
b630098273c4b448fc986ed96b56129e8250ee30 fixes this similar to to other listboxes in horizon
