### ISSUE TITLE
Schematic Editor Antenna symbol shows "unsupported orientation"

### ISSUE THREAD

**Issue by atoav** [carrotIndustries/horizon#135]
In the Schematic editor I get this display (I rotated the +12V powernet symbol to point up instead of down):  

![unsupported_orientation](https://user-images.githubusercontent.com/6620266/38676716-314aa848-3e5c-11e8-9f0e-41b77b0a8cb7.png)

This might be known, however I think it would be desireable to allow up-pointing antennas.

Edit: I see what this is – this is what he displays when you rotate it 90° or 270°. So he displays the right orientation, but internally sees the wrong orientation. This could be solved two ways:  
- Just skip the 90° and 270° rotational steps alltogether for these symbols. When people can't rotate to 90° or 270° they won't produce that error.
- Display the rotation and the warining instead of displaying only 0° and 180° (probably much easier to implement)

**Comment by carrotIndustries** [comment]
> Just skip the 90° and 270° rotational steps alltogether for these symbols. When people can't rotate to 90° or 270° they won't produce that error

I deliberately didn't do it this way so that the power symbols rotate in sync with everything else.

> Display the rotation and the warining instead of displaying only 0° and 180° (probably much easier to implement)
Implemented in 5f7c5969c24d3a9f95e5e617659429c8660a69d3
