### ISSUE TITLE
[UI] Part Editor: Inherit field logic

### ISSUE THREAD

**Issue by atoav** [carrotIndustries/horizon#137]
Let's say I have a description like `Super Precision Resistor` for the parent – if I want to change this Description to `Super Precision Resistor 100k 0.001% 1ppm/C 1000W` I have to rewrite the "Super Precision Resistor"-Part by hand for every new value of Super Precision Resistor.  

Maybe I get the idea of the description wrong, but I think it would make sense to _not_ delete the inherited value just because the Inherit-Button is deactivated. If one deactivates "Inherit" and the inherited value is completely out of place, one could easily delete it with <kbd>Ctrl</kbd>+<kbd>A</kbd> and then <kbd>DEL</kbd>. The case I pictured above might be quite common (except for the 1000W 1ppm resistor maybe), so it _could_ make sense to make this the default behaviour. What do you think?

**Edit:** and while I am at it – allowing Inheritance for the "Tags"-Field would save quite some work also. I saw that there is a `"inherit_tags": false` in the part-json files, so I assume this is planned?  

Horizon has the most enjoyable library/pool experience I had up to date and it can easily become _the_ next open source EDA solution everybody uses. That is why I decided to invest my time into improving it where I can help. If I get to granular, stop me or just write me a mail : )

**Comment by carrotIndustries** [comment]
Oops, looks like I forgot the new attributes (datasheet/description) when creating a part from another one.

Re tags: These can be inherited as well, the interface is just a little different. Seems like you simply overlooked the button ;)
