### ISSUE TITLE
Board Editor: Moving by entering number won't move smashed $RD

### ISSUE THREAD

**Issue by atoav** [carrotIndustries/horizon#141]
When I move a part with smashed `$RD` by entering new coordinates into the Position X or Position Y, the smashed `$RD` wont move with it, but stay at the place it was.

Expected behaviour: it should always stay relative to it's parents location and orientation.

Also: is there an easier way to re-align moved parts to the grid than setting it's coordinates to [0, 0] manually?

**Comment by carrotIndustries** [comment]
> Expected behaviour: it should always stay relative to it's parents location and orientation.

For me it does so, cannot reproduce.

> Also: is there an easier way to re-align moved parts to the grid than setting it's coordinates to [0, 0] manually?

The cursor snaps to the center of parts, so move the cursor so that it snaps to the center of a part, then start the move tool and the cursor with the part attached will snap to the grid.

**Comment by atoav** [comment]
See here, with this smashed part. When I move it via <kbd>m</kbd> it works just fine. 
As soon as I move it via entering a number and pressing <kbd>⏎</kbd> I only affect the part and not it's smashed `$RD`.
![offset](https://user-images.githubusercontent.com/6620266/39093637-d7d108b0-4622-11e8-9d9c-f53e57662540.gif)  
I understand that could be good for some situations, but I think the behaviours of moving by <kbd>m</kbd> and moving via absolute value should be the same.

**Comment by carrotIndustries** [comment]
Oh, I see. I thought you were referring to the move exactly tool.
