### ISSUE TITLE
Error 3 on Board Editor

### ISSUE THREAD

**Issue by atoav** [carrotIndustries/horizon#145]
I made a [simple test board](https://code.hfbk.net/t6/sdiy/tree/master/invoff/horizon/Invoff) for a small project, and upon putting it into a git the board editor exists with Error 3. I suspect that a `git clean` I ran deleted the vias folder.  

Is there any way of fixing this without redoing the board manually? : )

**Comment by carrotIndustries** [comment]
This commit makes the project manager recreate the vias directory if it is absent.

**Comment by atoav** [comment]
Thanks very much : )
