### ISSUE TITLE
Startup-Crash: yaml-cpp.dll missing

### ISSUE THREAD

**Issue by atoav** [carrotIndustries/horizon#146]
In one of the latest commits a error has been introduced:  
![2018-04-24 23_57_18-horizon-prj-mgr exe - system error](https://user-images.githubusercontent.com/6620266/39216328-795af41c-481b-11e8-9036-df03a417e707.png)  
Didn't had the time to pinpoint the exact build, but maybe it can be fixed without that information?

**Comment by carrotIndustries** [comment]
Issues of this kind really seem to be getting out of hand lately. Maybe it's time to add some check to the CI to verify that all DLLs are included...
