### ISSUE TITLE
Build does not run: libsodium-18.dll is missing

### ISSUE THREAD

**Issue by atoav** [carrotIndustries/horizon#147]
![libsodium](https://user-images.githubusercontent.com/6620266/39489179-f7a6c878-4d84-11e8-84a2-91b8225fe432.png)  
Time to integrate some check for missing libraries as you said : )

**Comment by carrotIndustries** [comment]
This one will fix itself once https://github.com/Alexpux/MINGW-packages/pull/3669 is merged

**Comment by carrotIndustries** [comment]
The latest build should fix this since my mingw PR got merged.

**Comment by atoav** [comment]
Now `libsodium-23.dll` is missing : /

![libsodium2](https://user-images.githubusercontent.com/6620266/39598616-72024e40-4f19-11e8-8b39-bdbf08bd509a.png)

**Comment by carrotIndustries** [comment]
Did 8aa7a151999cf29330d6ed59483c5fa2a2eeab5f fix it?

**Comment by atoav** [comment]
Yes, it works
