### ISSUE TITLE
Crash with schematic editor

### ISSUE THREAD

**Issue by atoav** [carrotIndustries/horizon#155]
Since the last few builds [this project of mine](https://code.hfbk.net/sdiy/invoff/tree/master/horizon/invoff) seems to crash:  
![2018-05-13 22_08_05-mingw runtime assertion](https://user-images.githubusercontent.com/6620266/39971386-77d48296-56fa-11e8-98b4-5e58f8d5a0f5.png)  

I didn't change anything since the last time I worked on it..?

**Comment by carrotIndustries** [comment]
oops, arcs and lines got mixed up during saving. 256b931c5189ff5dfb22a336a5a02596e5675fce fixes this

87da0f3f3d2e31d7e383205daada7e699203b435 makes the error while loading a log item instead of crashing the whole application

Looks like you may need to redraw some of your arcs/lines.
