### ISSUE TITLE
add install and dist target to makefile

### ISSUE THREAD

**Issue by steinm** [carrotIndustries/horizon#16]
I propose to add an 'install' and  'dist' target to the makefile. That would ease the creation of debian packages.

PREFIX=/usr
VERSION=$(shell git log -1 --date="format:%Y%m%d" --pretty="format:%cd")

install: install-bin

install-bin:
  install -d $(DESTDIR)$(PREFIX)/bin
  install -m 755 horizon-imp horizon-pool horizon-prj horizon-pool-update-parametric horizon-prj-mgr horizon-pgm-test horizon-pool-mgr $(DESTDIR)$(PREFIX)/bin

dist:
  tar -C .. -cJv --exclude=debian --exclude=horizon-$(VERSION).tar.xz --exclude-vcs --exclude-vcs-ignore --transform='s/horizon/horizon-$(VERSION)/' -f ../horizon-$(VERSION).tar.xz horizon

**Comment by carrotIndustries** [comment]
Seems like the dist target assumes the directory the source code lives in is called `horizon`, but looks good otherwise.

**Comment by carrotIndustries** [comment]
Obsolete due to upcoming move to cmake
