### ISSUE TITLE
Last build reintroduced icon issues

### ISSUE THREAD

**Issue by atoav** [carrotIndustries/horizon#160]
![icon](https://user-images.githubusercontent.com/6620266/40267648-820e1c80-5b60-11e8-9ccc-acdf0f0f4cff.gif)  
Maybe related to #130 or #126

**Comment by carrotIndustries** [comment]
Can't reproduce this issue.

**Comment by atoav** [comment]
On suspicion I restarted my system and couldn't reproduce after restart so I suggest to close it.
