### ISSUE TITLE
Two binaries, one icon

### ISSUE THREAD

**Issue by atoav** [carrotIndustries/horizon#163]
As for now we have two executables that have to be started seperately with the same icon. In the long run this needs to be solved in some way. As mentioned in #159 there are three obvious solutions:
1. the pool manager gets its own icon
2. the pool manager is to be opened from the prj-mgr (or the other way around)
3. a startup-window for both pool-mgr and prj-mgr  

Just because I had it lying around, here is a alternate icon draft. Any opinions?

| Name | Draft |
| ------ | ----- |
| Sky Pool 256x256  | ![sky_pool_256](https://user-images.githubusercontent.com/6620266/40315331-59fe96ae-5d1b-11e8-953d-9e7a032b0800.png)  |
| Sky Pool 64x64| ![sky_pool_128](https://user-images.githubusercontent.com/6620266/40315335-5a53eae6-5d1b-11e8-813b-b5618b2e56fe.png)  |
| Sky Pool 32x32 | ![sky_pool_32](https://user-images.githubusercontent.com/6620266/40315334-5a3787b6-5d1b-11e8-9c5b-f93999eb640d.png)  |
| Sky Pool 16x16 | ![sky_pool_16](https://user-images.githubusercontent.com/6620266/40315332-5a19f188-5d1b-11e8-8d62-230b49b294c5.png) |

**Comment by carrotIndustries** [comment]
>    the pool manager gets its own icon

From all options presented, this seems to be the most sensible one.



>   the pool manager is to be opened from the prj-mgr (or the other way around)

Doesn't make much sense TBH.

>    a startup-window for both pool-mgr and prj-mgr

As both (espescially the project manger) are some kind of launcher themselves, that would be kinda awkward.

**Comment by atoav** [comment]
> From all options presented, this seems to be the most sensible one.
Okay then we're on the same page, I also liked this variant the most. Like last time I will try to produce a few drafts for the pool managers logo.  

I will try to:
- keep it visually and color wise very close to the other icon (so it is clear they belong to the same package)
- avoid silly pool-related imagery (e.g. like my part scraping and generation script called `poolnoodle.py`).
- maybe it could also make a little sense. In the draft above I was inspired by the lines that you see when you list things, and it also doubles as shooting stars, but maybe for a outside person it is a bit too far fetched.  

In any case I will try to make a few drafts, so we don't have to take the first thing that we see.

**Comment by carrotIndustries** [comment]
4th Option that i'll probably go with: Combine pool and project manager into one application that transforms into the proper one depending on what's opened. This also helps to bring pools and projects closer together as needed for #165

**Comment by atoav** [comment]
Very cool, removes a lot of visual and mental clutter and works pretty well!
