### ISSUE TITLE
Pool Editor: Duplicate Symbol is not useful

### ISSUE THREAD

**Issue by atoav** [carrotIndustries/horizon#168]
**The problem:** one cannot change the unit after duplication. Therefore "Duplicate" is only useful to create symbol variations for existing unit.  

I imagine there is a reason why the unit is not changeable after symbol creation? I know that you _can_ change the underlying unit by replacing the old unit UUID in the symbols json file – an approach which worked all the time for me, but is certainly not user friendly.  

This may seem like a minor thing but helps keeping different symbols visually consistent.

**Comment by carrotIndustries** [comment]
Before  5c8b38f the preferred way to accomplish this was to duplicate the corresponding unit and to leave the button for duplicating symbol checked.
