### ISSUE TITLE
Some previously working 3D models not displaying anymore

### ISSUE THREAD

**Issue by atoav** [carrotIndustries/horizon#172]
Some previously working 3D models don't work anymore, e.g. the `PJ301M-12` (added via [PR 31](https://github.com/carrotIndustries/horizon-pool/pull/31))

I couldn't really pinpoint where this happened, but the step importer isn't really the most reliable. I am still trying to figure out which kinds of step data it wants to have.

**Comment by carrotIndustries** [comment]
There haven't been any significant changes to the step importer since its appearance. You may try importing the step model in kicad 5.0 and see what happens over there. If it's the same, file a bug with kicad.

**Comment by atoav** [comment]
I didn't manage to check it with kicad yet. I was never really totally literate in kicad, that is why testing this out involves some time effort to figure things out.   

In an effort to fix this for me I tried to re-import another model I made – I had the hope that it was just a a weird issue with the modelling process or the file formats. For some reason I don't even get a simple cube (made with FreeCAD) to display in the 3D-editor.   

I then tested with a step file that should work, e.g. the default pools `3d_models/passive/capacitor/C_1210_3225Metric.step` and it again didn't display anything in the Package Editors 3D Preview Window. I am quite sure this isn't intended behaviour, maybe it is a Windows issue?

**Comment by atoav** [comment]
**Update:** The same models that didn't show up in the Package Editor's 3D Preview window, seem to display perfectly fine in the Board Editor's 3D Preview window.

**Comment by atoav** [comment]
**Update 2:** I see there are two issues at play:  
1. The kicad importer really doesn't like step files that don't consist solids
2. The 3D-Preview doesn't display imported 3D files _until they have been saved and are re-read from the pool_

**Comment by atoav** [comment]
Okay it seems this has been fixed. Maybe I should add some details regarding 3D-Parts to the wiki?
