### ISSUE TITLE
Simplifying mask/paste polygon generation for complicated pad stacks

### ISSUE THREAD

**Issue by fruchti** [carrotIndustries/horizon#179]
It's very nice that Horizon supports arbitrary pad geometries, but making solder mask expansion/paste contraption parametric can be pretty hard. Having `expand-polygon` for padstacks as well with a similar "generate parameter program" button to the courtyard one would be a nice solution IMHO, but maybe you have another solution in mind?

Background: I'm currently trying to build this footprint:
![screenshot_2018-07-22 nvtfs5c478nl - power mosfet - nvtfs5c478nl-d pdf](https://user-images.githubusercontent.com/11243448/43048528-5f3a2fda-8de9-11e8-82fa-4ffb6e73a3f0.png)
and I really don't want to calculate all coordinates manually and use `set-polygon`.

**Comment by carrotIndustries** [comment]
ae33948912f0a5882357a26134689b87058c1347 makes expand-polygon available for padstacks as well

Mind that your given padstack might/will break the router since the router expects to only get convex pads. IIRC kicad solves this by triangulating the pad, so this shouldn't be too hard to fix

**Comment by carrotIndustries** [comment]
5c4ef924b69909cf773fcade8a40068795e50ea2 should enable non-convex pads

**Comment by fruchti** [comment]
Perfect! Working exactly as it's supposed to. Thanks a ton!
![2018-07-23-214937_2476x1488_scrot](https://user-images.githubusercontent.com/11243448/43099378-4b52f72a-8ec2-11e8-9dd6-65fd630df997.png)
