### ISSUE TITLE
Bus ripper orientation

### ISSUE THREAD

**Issue by endofexclusive** [carrotIndustries/horizon#185]
Bus rippers support this style:
![down](https://user-images.githubusercontent.com/2054878/43524560-e2dd3d4c-959f-11e8-98f7-982b52ddda99.png)
But not this:
![2018-08-01-152944_386x209_scrot](https://user-images.githubusercontent.com/2054878/43524648-14577ebe-95a0-11e8-82c8-79f1d5d95d01.png)

The `BusRipper` class has a `mirror` boolean which currently allows to mirror around the Y axis, but not the X axis. `mirror` could be changed to an `Orientation` instead to support pointing into one of four quadrants. 

Another approach would be to represent the ripper with an angle and length. That could in the long term get away with the 1.25 mm (fixed?) length.

**Comment by carrotIndustries** [comment]
While we're at it, should we support bus rippers on horizontal bus lines with the text going vertically? IMO it's not really worth the hassle since we'd end up with 8 orientations total and all sensibly-drawn symbols have their bus ports on the left/right side.

**Comment by endofexclusive** [comment]
In my opinion, vertical text in schematics is definitietely a thing to avoid. However, that is just an opinion and there could be situations where other factors can sanction it. I did a web search to try to find authoritative guidelines on schematic text orientation, but could unfortunately not find any. (But lots of opinions on forums etc.)

For Horizon, I would be happy with horizontal text only. If the text becomes to wide, then it could be shortened since it is local to the bus anyway.
                                                                                
If there is going to be a change in the implementation that breaks the file format, like substituting bool mirror into Orientation, then it could be an appropriate time to also add support in the file format for the arbitrary text orientation. Even though the aim is to currently not support it, it would prevent the file format from being a blocker for a future implementation.

**Comment by carrotIndustries** [comment]
File format changes aren't that bad as long as the current version of horizon can open files created with older versions.

I don't think that arbitrary length/angle is something desirable since everything on the schematic is supposed to be aligned to the 1.25mm grid.

**Comment by endofexclusive** [comment]
The bus ripper orientation works very well here with 7adfac9. Thank you!
