### ISSUE TITLE
Schematic editor: no connect symbol

### ISSUE THREAD

**Issue by endofexclusive** [carrotIndustries/horizon#190]
I can not find out how to mark a symbol pin as "no connect" in the schematic editor.

It can look like this in Orcad Capture:
![orcad](https://user-images.githubusercontent.com/2054878/43719866-2ffd8918-998f-11e8-9460-19b7f498339d.png)
and Altium:
![altium](https://user-images.githubusercontent.com/2054878/43719872-357c41ea-998f-11e8-838b-b62807f5c832.png)

It could possibly be "emulated" in Horizon with a dedicated part which has an empty package and/or no pad->pin mapping. However, that probably requires a short net segment between the symbol pins, and does not convey "no connect" information to the rule checker.

**Comment by carrotIndustries** [comment]
Use the "Set all unconnected pins NC" tool on a symbol to make all unconnected pins NC pins. To change individual pins use the "Set pins NC" tool.

**Comment by endofexclusive** [comment]
It works perfectly. Thanks!
Added the key combination "p n" on my setup.
