### ISSUE TITLE
Usefulness of “keep horizontal” for pin names

### ISSUE THREAD

**Issue by fruchti** [carrotIndustries/horizon#194]
It does exactly what its name says, but I can't really think of a context where this behaviour would be desirable.
![2018-09-13-172308_2476x1488_scrot](https://user-images.githubusercontent.com/11243448/45498311-0e620c80-b77a-11e8-92f6-7e60f3dbbc8c.png)
Under normal circumstances it looks bad in 3/4 cases. Maybe a “rotate pin name by 90 degrees” option is better here?

**Comment by carrotIndustries** [comment]
a43aeed62d9b786c7cfab4b201635f7a4b5f59bd fixes the text placement

The idea behind this feature is to avoid vertical text in all orientations.

**Comment by fruchti** [comment]
Definitely looking better! Yet I still don't really know when this would be nice to have. Did you have an example in mind for this feature?

Would splitting this configuration into two options like

* name perpendicular to pin and
* keep pin name orientation when rotating symbol

be an option?

**Comment by carrotIndustries** [comment]
This feature came to be since vertical text is something i'd like to avoid wherever possible, hence the option to force the text so stay always horizontal.

Are there any use cases where that'd be undesired?

**Comment by fruchti** [comment]
I'm absolutely with you in that vertical text should be avoided. The problem here is the rotation of the labels then changes relative to the symbol, so the pin generally needs more space inside the “symbol body”. The symbol pictured above would need to be larger even with the fixed pin name placement (`VDD` collides with the diode with this size). In other words, even when it doesn't help in 99% of the cases, I'd have to make the symbol larger for the 1% we almost never see.

Imagine a microcontroller symbol with pins mostly on the left and right sides with a few power supply pins on the top and bottom (assuming we decide on this layout). The standard orientation will be used in pretty much every case. Having the power supply pins' names horizontal too would look nice and also save space in most cases. If you rotate the part, though, it'd get difficult: You wouldn't keep all pins horizontal because that would require tremendous space around each pin so the names wouldn't collide. Yet the power supply pin names would change orientation and require that space, voiding one of the advantages.

I try to keep my symbols as compact as possible while keeping them visually structured. This feature in its current form doesn't really help me there and a think a good compromise between keeping pin name horizontal all the time and reasonable symbol compactness would be achievable pretty easily.

**Comment by fruchti** [comment]
Looks good, thanks!
