### ISSUE TITLE
[UI] Change net label default size from 1.5 to 1.3

### ISSUE THREAD

**Issue by atoav** [carrotIndustries/horizon#203]
I suggest a change of the default sizes of netlabels from 1.5 to something smaller because of how they look with the default spaced pins: 

1.5  
![1 5](https://user-images.githubusercontent.com/6620266/48191926-b2b19b00-e346-11e8-9524-ccdbe0541686.png)  

1.3  
![1 3](https://user-images.githubusercontent.com/6620266/48191938-b9401280-e346-11e8-9227-d0daec767a88.png)  

1.329 (this is roughly where the lines of the labels line up)  
![1 329](https://user-images.githubusercontent.com/6620266/48192084-1d62d680-e347-11e8-9273-1a590a5630e5.png)

Of course this will always be a compromise between font size and grapcial looks – maybe the font could be bigger and the label margins a tiny bit smaller, etc.  I think the default solution should be something that works well on commonly used parts without a need for manual adjustments that is why I think non-overlapping labels would be nice : )

**Comment by atoav** [comment]
Closed, I am an Idiot, this seems to work as soon as you name the nets for some reason?

**Comment by atoav** [comment]
Okay maybe I am not an idiot, it seems that certain characters have a higher line height than others:  
n the case of "? plz fix" the questionmark is higher than the rest. In the case of the offsheet references it is the square brackets.  

You can see here (all with 1.5mm height) how the first two labels are well spaced, while the last 3 labels all have different heights because the square brackets are higher than the questionmark which is in turn higher than a lowercase label composed of dots:  

![offsheet_references](https://user-images.githubusercontent.com/6620266/48195229-54d58100-e34f-11e8-9acf-dca51e887728.png)


Maybe this is intentional by design, but I'd suggest to look into keeping it at the same height at least for all regular labels

**Comment by carrotIndustries** [comment]
971b2a4c421c66346b044e4fa1c5fa82366953ca persists net label size in tools

**Comment by atoav** [comment]
Looks better now : )
