### ISSUE TITLE
[UI] Add Snap to Axis for duplicate

### ISSUE THREAD

**Issue by atoav** [carrotIndustries/horizon#205]
When I move stuff with <kbd>m</kbd> I can toggle between free movement, constrained to X and constrained to Y with <kbd>/</kbd>.  

I'd love to have the same ability after duplicating parts. Sometimes you duplicate a thing but you only want to move it down without moving it left and right accidentally.

**Comment by carrotIndustries** [comment]
a98b41664cd8d3f01b0d760a171b74fbf7e39e8d somehow fixes this, but the restriction is relative to each individual paste, i.e. is reset after each click to paste

**Comment by atoav** [comment]
I think this is good enough, thanks for the quick fix!
