### ISSUE TITLE
Pool manager: Replace line breaks from input fields

### ISSUE THREAD

**Issue by atoav** [carrotIndustries/horizon#212]
While creating parts I often paste text (e.g. a MPN) into the according field. These fields will _not_ display line breaks, but they will be shown in the parts list later. This means there are three possible outcomes:
1. I just don't realize that there was a line break
2. I have to retype the thing
3. I have to paste it into some other field that replaces `\n` and copy it again

All of these are not really to be desired.

## Solution
Either:
* Replace line breaks in the fields
* Allow line breaks, but display them

**Comment by carrotIndustries** [comment]
Ok, on Linux these show up as boxes
![2018-12-04-002419_146x51_scrot](https://user-images.githubusercontent.com/877304/49408033-fedfd780-f75a-11e8-8088-7b883a3bd868.png)

Gtk offers a simple option to work around this by truncating everything after the first `\n`.
Alternatively, writing some custom code that hooks into the paste event might be the way to go.

**Comment by atoav** [comment]
Ah okay, now I get the rationale. On Windows they are displayed as zero space ehich essentially makes them invisible in the text field but visible in the list.

Best from a usability perspective would be to just replace “\n” with space.

**Comment by carrotIndustries** [comment]
So I've had a a chat with Gtk folks on their IRC channel: There's no sensible way to intercept paste data on it's way to the entry, the only workable workable solution on the entry level would be to truncate everything after the first newline.

How about something like this instead? The black box is a tooltip that appears after hovering over the icon.
![warning](https://user-images.githubusercontent.com/877304/49478674-ba1e7400-f820-11e8-88a0-4c4c58d8d456.png)
