### ISSUE TITLE
[UI] Package Editor layer reminders

### ISSUE THREAD

**Issue by atoav** [carrotIndustries/horizon#225]
This is a proposal for reminder texts on what the individual selected layers are meant to be. I am arguably one of the users who use the package manager often and even I forget at times which layer was meant to do what, when I didn't touch the editor for a few weeks.  

I then usually tend to go back to the wiki page, which details it more or less. I wondered, maybe it would be a good idea to use the unused area within the left sidebar to display this information directly in the software?  

This would both help long time users who forgot whether it was the package layer or the assembly layer which needs a `$RD` and new users who are really lost what these layers are actually meant to do.  

Maybe we need to shorten the text a little, or make things more concise, but what do you guys think about this?

![a](https://user-images.githubusercontent.com/6620266/51437910-ef820280-1ca4-11e9-9908-18f6f5e4d492.png)

**Comment by carrotIndustries** [comment]
Great idea! I just implemented the code side of things in https://github.com/carrotIndustries/horizon/tree/layer_help

The only thing left to do is to add useful content.
The content goes in https://github.com/carrotIndustries/horizon/tree/layer_help/src/imp/layer_help
with the file name being the layer number (see https://github.com/carrotIndustries/horizon/blob/master/src/board/board_layers.hpp).

You can use https://developer.gnome.org/pango/stable/PangoMarkupFormat.html and links to tools and actions (see https://github.com/carrotIndustries/horizon/blob/layer_help/src/imp/layer_help/0)
For the tool and action names see https://github.com/carrotIndustries/horizon/blob/layer_help/src/imp/action_catalog.cpp

**Comment by atoav** [comment]
I am working on it, I think I can manage something over the weekend or so.

**Comment by carrotIndustries** [comment]
Did you run make in in the MSYS2 or MINGW64 shell? The latter is the correct one.

**Comment by atoav** [comment]
My build result of running `make  -j 8` for the branch seems to be missing some DLLs. They are not missing on the AppVeyor Artifact however. The libraries in question are:
- libwinpthread-1.dll
- libgcc_s_seh-1.dll
- libatkmm-1.6-1.dll
- libstdc++-6.dll

## Prompts

![2019-01-26 12_34_52-horizon-eda exe - system error](https://user-images.githubusercontent.com/6620266/51786698-5b161500-2168-11e9-9ea8-465a18d0d9a7.png)
![2019-01-26 12_35_15-horizon-eda exe - system error](https://user-images.githubusercontent.com/6620266/51786699-5b161500-2168-11e9-8aa6-8024fdb2cc87.png)
![2019-01-26 12_35_22-horizon-eda exe - system error](https://user-images.githubusercontent.com/6620266/51786700-5b161500-2168-11e9-94a6-9d178dbf091b.png)
![2019-01-26 12_35_28-horizon-eda exe - system error](https://user-images.githubusercontent.com/6620266/51786701-5baeab80-2168-11e9-8ab5-ebab3e51da8a.png)

**Comment by carrotIndustries** [comment]
How did you start `horizon-eda.exe`? Either start it from the ming64 shell by running `./horizon-eda.exe` or run the `make_bindist.sh` script and double-click on `horizon-eda.exe` in the `dist/horizon` directory. Double-clicking on `horizon-eda.exe` in the build directory won't work since windows doesn't know where to look for the DLLs.

**Comment by atoav** [comment]
Gotcha : )

**Comment by atoav** [comment]
I have a proposal in PR https://github.com/carrotIndustries/horizon/pull/227

**Comment by carrotIndustries** [comment]
closing since we now have this feature
