### ISSUE TITLE
Outline combined from lines and arcs buggy

### ISSUE THREAD

**Issue by ruabmbua** [carrotIndustries/horizon#238]
When I create an outline for my PCB, which has round corners (by combining arcs with lines), the 3D preview begins to glitch. The substrate is not rendered at all.

I am not sure if this only affects the 3d rendering, or if there is something more fundamental, which causes the bug.

I will try to create some planes in various shapes, and see if I can trick e.g. the plane filling into not working.

Off topic:

By the way, really great work on this app!
I am not that long into electronics (software engineering background), but I began with eagle (frustration), switched to KiCAD (works for me, but meh... ), and now I stumbled upon this project. I will give it a shot with my new hobby project, maybe even stay as a long term user. 
I was really surprised how many features are already working. Especially when compared to LibrePCB which I tried before (to be fair, I guess this project is way older).

**Comment by carrotIndustries** [comment]
> When I create an outline for my PCB, which has round corners (by combining arcs with lines)

Did you create the outline using lines and arcs or using a polygon? In horizon the board outline is represented by a polygon and not by a line loop as in other EDA applications.

e97b782170ab3755848c5f896c9537dadb72f728 checks for this in the preflight checks

**Comment by ruabmbua** [comment]
Thanks!
