### ISSUE TITLE
Clang-format inconsistencies

### ISSUE THREAD

**Issue by carrotIndustries** [carrotIndustries/horizon#243]
I just upgraded my copy of clang-format to 8.0, which seems to format things differently than the clang-format 5.0 used in the stylecheck CI:

https://circleci.com/gh/carrotIndustries/horizon/1017?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

@korken89 Any idea how to fix or work around this?

**Comment by korken89** [comment]
Hey, sorry for the late reply.
In the settings we install the version of clang-format to use - you can just update to 8.0. :)

You might need to add the PPA for 8.0 though - after that is should be fine.

**Comment by carrotIndustries** [comment]
fixed in 1aef0b94f73b141f485678feb1066a49070ac6cc
