### ISSUE TITLE
PDF Export: Black Line on Left and Top Edge

### ISSUE THREAD

**Issue by atoav** [carrotIndustries/horizon#244]
This is a purely cosmetic issue: 
When a PDF is exported there are two black lines in the resulting PDF on the very top and on the very left edge of the PDF's outline.  

I converted the pdf to an image and cropped the top left corner out to illustrate it:  
![frame](https://user-images.githubusercontent.com/6620266/55654903-eb20ac80-57f2-11e9-9b3d-32bbbeb294a0.png)  
(The inner two lines come from the A4 Landscape frame, while the outer two seem to be added from the exporter without beeing present in either frame nor schematic).

**Another thought:** the default margin of the frames seem to be 2.5 mm from the edge. Most printers need a margin of ~4-5 mm to print. Maybe it would be a better idea to change these frames to 5 mm margins for a better compatibility?

**Comment by carrotIndustries** [comment]
The frames are part of the pool, so feel free to modify them to your needs or open a PR in the pool repo.

The original issue has been fixed in the commit referenced.
