### ISSUE TITLE
podofo Missing

### ISSUE THREAD

**Issue by cortesis** [carrotIndustries/horizon#248]
Whilst trying to install horizon on Arch, following the build-instruction in the docs, there was an error that <podofo/podofo.h> is missing. Please "podofo" to the install instruction (e.g. pacman -S podofo)

**Comment by carrotIndustries** [comment]
Fixed in https://github.com/carrotIndustries/horizon-docs/commit/7a31432487928f17766b090dcf29341d0001be3b
