### ISSUE TITLE
New part - Bring window to front

### ISSUE THREAD

**Issue by greenscreenflicker** [carrotIndustries/horizon#28]
It would be convinient when clicking on "place part" in the schematic editor it would bring the part window to front.

**Comment by carrotIndustries** [comment]
Based on your previous issue, I'm guessing you're using windows.
Actually I'm trying to do show the window. Does the window light up in the taskbar?

**Comment by greenscreenflicker** [comment]
@carrotIndustries : Yes, windows.
The window blinks in the task bar, but does not come to front.
Blinking in taskbar, see img below.
![grafik](https://user-images.githubusercontent.com/17407241/34151629-2d64b0fc-e4ac-11e7-8c37-18c0a4ba96e1.png)

**Comment by carrotIndustries** [comment]
Unfortunately, that's a limitation arising from the fact that the schematic editor and the project manager that the part browser window belongs to are separate processes. To protect the user from nasty applications, Windows doesn't allow applications other than the one with input focus to bring windows to the front. (At least, that's how I understood it)

**Comment by greenscreenflicker** [comment]
Just found out this: Pressing pp (Place part) puts the window to the front and works. However clicking on the button, does not put it to front.

**Comment by greenscreenflicker** [comment]
@carrotIndustries : New discovery: The window is already there and is therefore only highlighted. 
If a part is placed, this window should close automatically. Then, when opening a new window, the window comes to front.
