### ISSUE TITLE
Poolmanager: Clicking on schematic needs long time to load.

### ISSUE THREAD

**Issue by greenscreenflicker** [carrotIndustries/horizon#30]
Clicking in the pool manager (schematic) needs a long time to load (10 sec.). Maybe there's optimisation potential.

**Comment by greenscreenflicker** [comment]
same thing with "packages"

**Comment by carrotIndustries** [comment]
That's the interactive manipulator starting up in it's own process. On my machine (2015 Ultrabook i7, SSD, Linux) the interactive manipulator starts up in next to no time.

Running the interactive manipulator within the same process as the pool manager would reduce stability, so it's going to stay like this in the near future.
