### ISSUE TITLE
Package editor: Duplicate option for lines / pads

### ISSUE THREAD

**Issue by greenscreenflicker** [carrotIndustries/horizon#32]
A duplicate option would be nice in the package editor.
![grafik](https://user-images.githubusercontent.com/17407241/34354562-71d0b226-ea2f-11e7-8045-99165fdd5a78.png)

**Comment by carrotIndustries** [comment]
It's there, but not in this context menu: Just press Ctrl-d

**Comment by greenscreenflicker** [comment]
@carrotIndustries 👍 Thanks for the tip, that works. I propose , to do to things for user comfort:

- [ ] Add to help menu
- [ ] Add to the dropdown menu for user comfort.

**Comment by carrotIndustries** [comment]
duplicate and copy are already in the key sequences list
