### ISSUE TITLE
Package editor: Typing text slow

### ISSUE THREAD

**Issue by greenscreenflicker** [carrotIndustries/horizon#34]
Typing information to text entry is slow. A recent machine (2015er i7 Windows 10) is used.
![grafik](https://user-images.githubusercontent.com/17407241/34363156-e8038316-ea79-11e7-87aa-8a49163cfdc1.png)

**Comment by carrotIndustries** [comment]
This has to be a Gtk issue since there isn't any specific handlers for the changed signal. Is this an issue in other entries as well.

**Comment by greenscreenflicker** [comment]
@carrotIndustries : Use the enter handler, so it updates only when pressing enter.

**Comment by carrotIndustries** [comment]
I dont't connect to the "change" event, so none of my code is running while typing.
