### ISSUE TITLE
Pool manager: Does not rember last opened pool

### ISSUE THREAD

**Issue by greenscreenflicker** [carrotIndustries/horizon#35]
Restarting the pool manager does not rember the old used pools. As you like to have only one pool it would be best if you would start directly into the pool.

Also it would be nice to have a button "get pool" and "update pool" to get it from git.

![grafik](https://user-images.githubusercontent.com/17407241/34363311-3ffc719e-ea7b-11e7-8b32-d70e3a39119a.png)

**Comment by carrotIndustries** [comment]
The download button is there in the latest windows release, an improved recent chooser is WIP right now.

**Comment by greenscreenflicker** [comment]
@carrotIndustries : Yes, i now got the download option and the update option after updating the software. However, the pool manager does not remember the last used pools.
![grafik](https://user-images.githubusercontent.com/17407241/34408178-8d1ce34e-ebc2-11e7-90a6-86c4a1370ac7.png)

**Comment by carrotIndustries** [comment]
Fixed in https://github.com/carrotIndustries/horizon/commit/c53bae290fc869f0eef677f1e5fb352cf071daec
