### ISSUE TITLE
Part Editor: Add datasheet field

### ISSUE THREAD

**Issue by greenscreenflicker** [carrotIndustries/horizon#37]
It would be nice to have a datasheet field. As you are requested to add non-generic parts, the datasheet would be required to verify the correct footprint. Also a datasheet helps to in the verification process during schematics creation.
![grafik](https://user-images.githubusercontent.com/17407241/34408856-81c14b12-ebc6-11e7-81f7-6cd55c8cc04a.png)

**Comment by carrotIndustries** [comment]
fixed in a016c9e97d0ab4e0c149e8b498e7e04a5e695fb1
