### ISSUE TITLE
Schematics Editor: Net Label can only be chagend when connected to a net.

### ISSUE THREAD

**Issue by greenscreenflicker** [carrotIndustries/horizon#38]
![grafik](https://user-images.githubusercontent.com/17407241/34409692-a66263ca-ebcb-11e7-923d-9436264a43d4.png)
The net label can only be connected, if a it is connected to a net. It would be nice, if the value could be edidited before.

**Comment by carrotIndustries** [comment]
That's not how net labels work in horizon: https://github.com/carrotIndustries/horizon/wiki/Schematic-editor#nets-and-net-segments
