### ISSUE TITLE
Schematics Editor: Power symbols cannot be rotated.

### ISSUE THREAD

**Issue by greenscreenflicker** [carrotIndustries/horizon#39]
Power symbols cannot be rotated. That strategy might work for GND, however for Vcc it looks silly.
![grafik](https://user-images.githubusercontent.com/17407241/34409814-861d36de-ebcc-11e7-88f9-a9b8a5559953.png)

**I propose to add different symbols where the user can chose what symbol he likes.**

**Comment by carrotIndustries** [comment]
For now, power nets are supposed to be only used for GND, so I updated the documentation to reflect this: https://github.com/carrotIndustries/horizon/wiki/Schematic-editor

**Comment by carrotIndustries** [comment]
Since https://github.com/carrotIndustries/horizon/commit/40d3089e6fdf6a691baa863ab44f49d2b9523635 more power symbols are available
