### ISSUE TITLE
Backward compatibility (loading old files)

### ISSUE THREAD

**Issue by greenscreenflicker** [carrotIndustries/horizon#43]
For now, it not tragic: But by adding the part description, it causes file corruptions. Maybe you find a method to fix this (maybe if something is not found, leave it empty...)
![grafik](https://user-images.githubusercontent.com/17407241/34466636-ffc6b0f8-eeda-11e7-9be1-b4469b015761.png)

**Comment by greenscreenflicker** [comment]
I guess it's the pool. Right?

**Comment by carrotIndustries** [comment]
Run the pool manager first and click on update pool to update the database schema.

**Comment by greenscreenflicker** [comment]
Works now fine for me. Thanks for your work @carrotIndustries .
