### ISSUE TITLE
Pool manager: Downloading pools fails

### ISSUE THREAD

**Issue by greenscreenflicker** [carrotIndustries/horizon#44]
![grafik](https://user-images.githubusercontent.com/17407241/34466811-863d0e3e-eee0-11e7-8a4a-3857d697be1d.png)
See image...

**Comment by carrotIndustries** [comment]
Did you use the zip or did you build it yourself? In the latter case, you'll have to copy the cert bundle to the application directory. I updated the documentation to mention this: https://github.com/carrotIndustries/horizon/wiki/Building-horizon-on-Windows#running

When reporting issues, please specify which build you're using. It's shown in the pool/project manger start page.

**Comment by greenscreenflicker** [comment]
@carrotIndustries : I propose to add the copy instructions to ./make_bindings.sh for an improved user experince. (And yes, building myself.)

**Comment by carrotIndustries** [comment]
The `make_bindist.sh` script already copies the certificates to the output directory.

**Comment by greenscreenflicker** [comment]
@carrotIndustries : I see it in the script too, i agree. However, it does not work for me in the script. Maybe you can test it again, plz?
If i copy the file manually, it works. So the cp instruction seems to fail. Maybe you can debug that...
