### ISSUE TITLE
Compile fails in current version

### ISSUE THREAD

**Issue by greenscreenflicker** [carrotIndustries/horizon#46]
Compile fails in 9f8fa5b
![grafik](https://user-images.githubusercontent.com/17407241/34480783-b1184f14-efae-11e7-9e7d-8135def1c77e.png)

**All libs are up to date**

**Comment by carrotIndustries** [comment]
Haven't seen this before. You may try doing a full rebuild by issuing `make clean` before building.

**Comment by greenscreenflicker** [comment]
@carrotIndustries : I did a clean before. Doesn't solve it.

**Comment by carrotIndustries** [comment]
This is due to the mingw people forgetting to recompile yaml-cpp after a boost update. When rebuilding yaml-cpp, the issue goes away. Unfortunately there's an issue with the latest yaml-cpp that needs to be sorted out before rebuilding the package: https://github.com/jbeder/yaml-cpp/issues/551

**Comment by greenscreenflicker** [comment]
Thanks for sorting out.
