### ISSUE TITLE
Pool manager: GTK warnings

### ISSUE THREAD

**Issue by greenscreenflicker** [carrotIndustries/horizon#47]
I get the following warnings from GTK when opening the pool manager, clicking on one pool, clicking there on packages, and then closing it. 

The output i get is below. I'm aware, that these are only warnings, but they seem to be new, so maybe you find a possibility to fix this.

$ ./horizon-pool-mgr.exe
SELECT parts.uuid, parts.MPN, parts.manufacturer, packages.name, GROUP_CONCAT(tags.tag, ' '), parts.filename, parts.description FROM parts LEFT JOIN tags ON tags.uuid = parts.uuid LEFT JOIN packages ON packages.uuid = parts.package WHERE parts.MPN LIKE ? AND parts.manufacturer LIKE ? AND (parts.entity=? or ?) GROUP BY parts.uuid  ORDER BY parts.MPN COLLATE naturalCompare ASC
SELECT parts.uuid, parts.MPN, parts.manufacturer, packages.name, GROUP_CONCAT(tags.tag, ' '), parts.filename, parts.description FROM parts LEFT JOIN tags ON tags.uuid = parts.uuid LEFT JOIN packages ON packages.uuid = parts.package WHERE parts.MPN LIKE ? AND parts.manufacturer LIKE ? AND (parts.entity=? or ?) GROUP BY parts.uuid  ORDER BY parts.MPN COLLATE naturalCompare ASC
close

(horizon-pool-mgr.exe:16964): Gtk-WARNING **: Allocating size to gtkmm__GtkBox 00000000185d1420 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

**Comment by carrotIndustries** [comment]
I looked into these warning some time back but couldn't quite figure out what I'm doing wrong. So far, I didn't see anything wrong with the UI, so we should be fine to ignore these warnings.
