### ISSUE TITLE
Pool manager: Loading old pools the remote option is missing.

### ISSUE THREAD

**Issue by greenscreenflicker** [carrotIndustries/horizon#48]
When loading old pools (before the datasheet option was implemented), the remote option is missing.
I do not know, if this is intention. If yes, you can close this issue.
Version: e3d3c6f

**Comment by carrotIndustries** [comment]
The remote tab requires a clone of the upstream repository to be present in the `.remote` directory in the pool. This documented on the wiki: https://github.com/carrotIndustries/horizon/wiki/Working-with-the-Pool-Manager-and-Part-Wizard#using-the-github-integration

To get your parts from your old pool to the newly downloaded one, simply copy the required json files to the new one and run a pool update.
