### ISSUE TITLE
wiki update for "Building-horizon-on-Linux.md"

### ISSUE THREAD

**Issue by peterus** [carrotIndustries/horizon#49]
Hi!

I was compiling horizon on Arch Linux and wanted to add my dependencies to the wiki. Here is what i wanted to add:

On Arch Linux run (list may not be complete):
```
sudo pacman -S yaml-cpp sqlite librsvg libepoxy gtkmm boost glm libcurl-gnutls
```

**Comment by carrotIndustries** [comment]
I actually already got a list of dependencies in the AUR package. Now, these are in the wiki as well.
