### ISSUE TITLE
Package editor: Display error msg when saving footprint with empty name

### ISSUE THREAD

**Issue by greenscreenflicker** [carrotIndustries/horizon#52]
It happened to me, that I saved my package and I forgot to label it. It would be nice if the program would remind me at saving, that there is a name required to save.
![grafik](https://user-images.githubusercontent.com/17407241/34569055-e44ff1ba-f167-11e7-8721-e57a476079ce.png)

**Comment by carrotIndustries** [comment]
Technically, the name isn't required. Closing since this is checked for in the in the design rules as of https://github.com/carrotIndustries/horizon/commit/6e49cb9e8d11541f534cf21c770ab515ec5e051a
