### ISSUE TITLE
Package editor: Merge fails

### ISSUE THREAD

**Issue by greenscreenflicker** [carrotIndustries/horizon#56]
The merge fails due to the slash problem...

![grafik](https://user-images.githubusercontent.com/17407241/34608121-2ec60df6-f217-11e7-908f-cdb68ba139f0.png)

**Comment by carrotIndustries** [comment]
Unfortunately, I can't test on windows right now, does https://github.com/carrotIndustries/horizon/commit/1c4579438f84bd6800374fa33b5c41f729b1f8c2 fix it?

**Comment by greenscreenflicker** [comment]
@carrotIndustries Works great now. Thanks.
