### ISSUE TITLE
Part-specific 3D models

### ISSUE THREAD

**Issue by fruchti** [carrotIndustries/horizon#58]
I think 3D models should be assigned to parts rather than packages. There are many cases of parts sharing the same footprint which should have different 3D models, for example:
- Parts with different possible heights, like electrolytic capacitors or pin headers
- Parts in different colours (like LEDs)

Creating the same package twice for these cases seems rather redundant to me.

Instead of setting the 3D model directly for a part, the package could also have a list of alternative 3D models, from which one can be chosen for each part.

**Comment by carrotIndustries** [comment]
You're the second one to comment on this, so seems like that's a thing.

> Instead of setting the 3D model directly for a part, the package could also have a list of alternative 3D models, from which one can be chosen for each part.

That's probably what I'll implement, since that way on can see the 3D models in conjunction with the footprint.

**Comment by greenscreenflicker** [comment]
@carrotIndustries I agree with @fruchti viewpoint.
