### ISSUE TITLE
Footprint Editor: No courtyard found

### ISSUE THREAD

**Issue by greenscreenflicker** [carrotIndustries/horizon#64]
![grafik](https://user-images.githubusercontent.com/17407241/34905563-62a5810c-f85b-11e7-8a7b-90e8c2a4a2f5.png)
I get the following error message. Maybe you can explain the msg to me.

I attach you the footprint.
[sot23-5-rect.zip](https://github.com/carrotIndustries/horizon/files/1628266/sot23-5-rect.zip)

**Comment by carrotIndustries** [comment]
The file you attached doesn't contain a courtyard polygon. Add one that matches the specifications given in the error message.

**Comment by greenscreenflicker** [comment]
@carrotIndustries  It's weired, look at the image above, there's a courtyard polygon.  Sorry, I'm afarid i just do not understand.

**Comment by carrotIndustries** [comment]
The file you sent doesn't contain one. Maybe you attached the wrong one?

**Comment by greenscreenflicker** [comment]
Okay, problem solved: I had serveral countyards in the design, but one rectange was only one line. So deleting this, solved everything. 
For the rulechecker there should be an option that only one countyard layer is inside.
