### ISSUE TITLE
DXF import in the board editor

### ISSUE THREAD

**Issue by fruchti** [carrotIndustries/horizon#66]
It would be handy to be able to directly import a DXF file for the outline layer.

**Comment by carrotIndustries** [comment]
The tool is already there, just hit space and search for dxf. b319bdfe210cfaf0e6edc06845db626d58290603 adds it to the hamburger menu for improved discoverability.

Anyhow, this tool imports the dxf file as lines, whereas the outline has to be defined as a polygon. To make this tool useful for your purpose, we'd need another tool for converting line loops into polygons. Pull requests are welcome :)

**Comment by fruchti** [comment]
It would be great if the line loop to polygon tool would work for arcs, too. Then, this issue would be resolved.

**Comment by carrotIndustries** [comment]
e6d524de3d362bf7d82861d209084ab7943d36f4 enables this, and 78de1aae7dca90fc2528fd2146ba8fd071c69cab makes polygons always render arcs, even if the two radii aren't the same

**Comment by fruchti** [comment]
Thanks a lot! It's working perfectly now.
