### ISSUE TITLE
3D Models not saved at footprint editor

### ISSUE THREAD

**Issue by greenscreenflicker** [carrotIndustries/horizon#73]
The 3D model addresses are not saved at the current 0069ae5fe195fd3833f7aaa3acae0e22ac0d7616 version. Also the merge 3d does not seem to work. Everytime reopening the 3d viewer from the pool manager the models are lost.

**Comment by carrotIndustries** [comment]
By addresses, you mean file name, right?
Did you press save in the package editor?

**Comment by greenscreenflicker** [comment]
@carrotIndustries : Yes, i didn't save it =( 

So I propose you add a dialog when quiting to ask that there were changes, and if you want to save it or not.
