### ISSUE TITLE
Disable "Save" button when there are no changes to save

### ISSUE THREAD

**Issue by jeanthom** [carrotIndustries/horizon#87]
Button is declared in `src/imp/imp.cpp` at line 247. `core.r->get_needs_save()` may be used to know when the button should be disabled (or not).

EDIT/ There is also a signal : `s_signal_needs_save`

**Comment by carrotIndustries** [comment]
This is currently blocked by #73 since non-tool interactions (such as editing rules) don't update the "needs save" flag.
