### ISSUE TITLE
Externalize CSS code into separate files

### ISSUE THREAD

**Issue by jeanthom** [carrotIndustries/horizon#89]
Currently CSS code is embedded in C++ source code, which is not practical (terrible CSS syntax highlighting, etc.). We could use `Gtk::CssProvider::load_from_file` and making it useable from the whole application.

**Comment by carrotIndustries** [comment]
Instead of using `load_from_file`, we should use `load_from_resource` so the binaries stay self-contained and don't have to go searching for files at runtime.

**Comment by jeanthom** [comment]
You're right. CSSProviders are used here :
 * [ ] src/imp/imp.cpp
 * [ ] src/imp/3d_view.cpp
