### ISSUE TITLE
Continuous integration on Linux platforms

### ISSUE THREAD

**Issue by jeanthom** [carrotIndustries/horizon#97]
Currently CI is only done on Windows (with Appveyor). I think we should have CI also for Linux targets. 

I don't know much about the free CI solutions on market, the only one I used was Travis CI (on my ![DirtyJTAG](https://github.com/jeanthom/DirtyJTAG) project) which unfortunately does not provides support for recent Ubuntu versions.

Maybe something Docker based or a self-hosted Jenkins could be a solution.

**Comment by carrotIndustries** [comment]
We do have circleci for linux: https://circleci.com/gh/carrotIndustries/horizon It's only used for verifying it builds though.

**Comment by jeanthom** [comment]
Uh, didn't know that !

Currently only Appveyor build status is displayed whenever I do a pull-request. Is it possible to get both Appveyor and Circle CI integration in GitHub ?

**Comment by carrotIndustries** [comment]
Seems like building PRs is off by default on circleci: https://circleci.com/docs/1.0/fork-pr-builds/ I enabled that setting, let's see if it actually works.

**Comment by jeanthom** [comment]
https://github.com/carrotIndustries/horizon/pull/98
Testing it right now.

**Comment by jeanthom** [comment]
Works ok !
